### ISSUE TITLE
Permissions can't be set from objectdetail page

### ISSUE THREAD

**Issue by livia-b** [SICASFoundation/smir-board#12]
Trying to set permission from the object detail page always results in a generic Error, while it is possible to set permissions from the "myData" view 

![image](https://cloud.githubusercontent.com/assets/2368524/17475387/0e04640c-5d5b-11e6-829c-624c8d492ea7.png)

**Comment by niklr** [comment]
Hi, I can't reproduce the described behaviour. What permissions are you trying to set and for which user/group/research unit?

**Comment by livia-b** [comment]
Hi, 
For example, go to  https://demo.virtualskeleton.ch/Home/ObjectDetail/27 to add "collaborate" permission to the group "One" .

At some point I had a similar problem also with the folders if I access them from the left menu in the detail page

**Comment by niklr** [comment]
Indeed, thank you for reporting the issue!
