### ISSUE TITLE
strange deletion of multiple folder behavior

### ISSUE THREAD

**Issue by mrkistler** [SICASFoundation/smir-board#14]
!all folders are empty!

single folder deletion from the single menu works, 
however, deletion of multiple selected folders (batch ->manage selected ->delete) does not work properly.
-> the popup does not close and does not reload the folder (cannot see if it worked).

**Comment by niklr** [comment]
kannst du das hier löschen und im dev-board hinzufügen? konnte es nicht reproduzieren.

**Comment by mrkistler** [comment]
moved to dev board, not reproducable
