### ISSUE TITLE
objects: version tag wrong

### ISSUE THREAD

**Issue by mrkistler** [SICASFoundation/smir-board#4]
The version tag of objects is displaying for both objects V1

Eg:
(from user baral1)
#14123 is V0
#99101 is V1

![firefox_2016-07-21_09-59-18](https://cloud.githubusercontent.com/assets/1415222/17015314/d8ee8fac-4f29-11e6-9bc3-0700e68baacf.png)
![firefox_2016-07-21_09-59-04](https://cloud.githubusercontent.com/assets/1415222/17015313/d8ed778e-4f29-11e6-8780-a7036c578ad0.png)

**Comment by niklr** [comment]
version tag removed for now
