### ISSUE TITLE
Problem downloading objects with rest api

### ISSUE THREAD

**Issue by livia-b** [SICASFoundation/smir-board#5]
I am trying to download some microct dcm series with the REST api, but I get HTTP Error 500 (tried with https://www.virtualskeleton.ch/api/objects/11669/download and https://www.virtualskeleton.ch/api/objects/11680/download ). I can download those objects just fine from the web interface. 
Other objects, such as 78615, can be downloaded from the REST  api (note that this is a smaller object, composed of only 1 nifti file)

**Comment by livia-b** [comment]
Also big files can't be downloaded with the rest api (for example https://www.virtualskeleton.ch/api/files/949086/download
https://www.virtualskeleton.ch/api/files/964237/download
https://www.virtualskeleton.ch/api/files/954164/download
https://www.virtualskeleton.ch/api/files/880902/download
https://www.virtualskeleton.ch/api/files/880901/download
)

**Comment by niklr** [comment]
Hi, this should have been fixed with the recent update. Could you please check if it is working now?

**Comment by livia-b** [comment]
Yes, it is working now, thanks!
